const STORAGE_KEYS = {
    SETTINGS: 'SETTINGS',
    APP_LANGUAGE: 'APP_LANGUAGE',
    IS_BATTERY_OPTIMIZATION_PROMPTED: 'IS_BATTERY_OPTIMIZATION_PROMPTED',
    TOKEN: 'TOKEN',
    BLOCK_END_TIMESTAMP: 'BLOCK_END_TIMESTAMP',
    COLLAPSED_RANKS: 'COLLAPSED_RANKS'
}

export default STORAGE_KEYS