
export const AUTH = {
    SET_USER: 'SET_USER',
    LOGOUT: 'LOGOUT',
    SET_ERROR: 'SET_ERROR',
    SET_AUTH_LOADING: 'SET_AUTH_LOADING',
    SET_PASSWORD_RESET: 'SET_PASSWORD_RESET',
}

export const RANK = {
    SET_RANKS: 'SET_RANKS',
    SET_RANKS_LOADING: 'SET_RANKS_LOADING',
    SET_RANKS_REFRESH: 'SET_RANKS_REFRESH',
    ADD_RANKS: 'ADD_RANKS',
    UPDATE_RANK: 'UPDATE_RANK',
    UPDATE_RANKS: 'UPDATE_RANKS',
    DELETE_RANK: 'DELETE_RANK',
    DELETE_RANKS: 'DELETE_RANKS',
    SET_SCRAPING_STATUS: 'SET_SCRAPING_STATUS',
    RESET_SCRAPING_STATUS: 'RESET_SCRAPING_STATUS',
    SET_RANKS_EDIT_MODE: 'SET_RANKS_EDIT_MODE',
    SET_RANKS_CHECK_LIST: 'SET_RANKS_CHECK_LIST',
    ADD_RANKS_CHECK_LIST: 'ADD_RANKS_CHECK_LIST',
    DELETE_RANKS_CHECK_LIST: 'DELETE_RANKS_CHECK_LIST',

    SET_RANKS_COLLAPSE: 'SET_RANKS_COLLAPSE',
    ADD_RANKS_COLLAPSE: 'ADD_RANKS_COLLAPSE',
    DELETE_RANKS_COLLAPSE: 'DELETE_RANKS_COLLAPSE',
}

export const SYSTEM = {
    SET_APP_STATE: 'SET_APP_STATE',
    SET_NETWORK: 'SET_NETWORK'
}

export const SETTINGS = {
    SET_SETTINGS: 'SET_SETTINGS',
    UPDATE_SETTINGS: 'UPDATE_SETTINGS',
    SET_SETTINGS_LOADING: 'SET_SETTINGS_LOADING',
}